import { Issue, Sprint } from './types';

export const initialSprints: Sprint[] = [
  {
    id: 'SPR-001',
    name: 'Q4 Foundation Sprint',
    status: 'Completed',
    startDate: new Date('2025-09-01'),
    endDate: new Date('2025-09-14'),
    createdAt: new Date('2025-08-25'),
  },
  {
    id: 'SPR-002',
    name: 'User Experience Improvements',
    status: 'Active',
    startDate: new Date('2025-09-15'),
    endDate: new Date('2025-09-29'),
    createdAt: new Date('2025-09-10'),
  },
  {
    id: 'SPR-003',
    name: 'Performance Optimization',
    status: 'Planned',
    startDate: new Date('2025-10-01'),
    endDate: new Date('2025-10-15'),
    createdAt: new Date('2025-09-20'),
  },
];

export const initialIssues: Issue[] = [
  {
    id: 'TSK-001',
    title: 'Implement user authentication system',
    description: 'Set up OAuth2 authentication with JWT tokens for secure user login',
    priority: 'P0',
    status: 'Done',
    assignee: 'Sarah Chen',
    sprintId: 'SPR-001',
    createdAt: new Date('2025-08-26'),
    updatedAt: new Date('2025-09-05'),
  },
  {
    id: 'TSK-002',
    title: 'Design database schema for projects',
    description: 'Create PostgreSQL schema with proper indexing and relationships',
    priority: 'P0',
    status: 'Done',
    assignee: 'Marcus Johnson',
    sprintId: 'SPR-001',
    createdAt: new Date('2025-08-27'),
    updatedAt: new Date('2025-09-06'),
  },
  {
    id: 'TSK-003',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    priority: 'P1',
    status: 'Done',
    assignee: 'Emily Rodriguez',
    sprintId: 'SPR-001',
    createdAt: new Date('2025-08-28'),
    updatedAt: new Date('2025-09-08'),
  },
  {
    id: 'TSK-004',
    title: 'Improve dashboard loading performance',
    description: 'Optimize queries and implement caching to reduce load time by 50%',
    priority: 'P1',
    status: 'In Progress',
    assignee: 'David Park',
    sprintId: 'SPR-002',
    createdAt: new Date('2025-09-12'),
    updatedAt: new Date('2025-09-20'),
  },
  {
    id: 'TSK-005',
    title: 'Add drag-and-drop for task reordering',
    description: 'Implement intuitive drag-and-drop interface for task prioritization',
    priority: 'P2',
    status: 'In Review',
    assignee: 'Sarah Chen',
    sprintId: 'SPR-002',
    createdAt: new Date('2025-09-13'),
    updatedAt: new Date('2025-09-22'),
  },
  {
    id: 'TSK-006',
    title: 'Redesign settings page UI',
    description: 'Modernize settings page with improved navigation and visual hierarchy',
    priority: 'P2',
    status: 'Todo',
    assignee: 'Lisa Thompson',
    sprintId: 'SPR-002',
    createdAt: new Date('2025-09-14'),
    updatedAt: new Date('2025-09-14'),
  },
  {
    id: 'TSK-007',
    title: 'Fix mobile responsive layout issues',
    description: 'Address layout breaking on mobile devices below 768px width',
    priority: 'P0',
    status: 'In Progress',
    assignee: 'Marcus Johnson',
    sprintId: 'SPR-002',
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-21'),
  },
  {
    id: 'TSK-008',
    title: 'Implement real-time notifications',
    description: 'Add WebSocket support for live notification updates',
    priority: 'P1',
    status: 'Todo',
    assignee: 'Emily Rodriguez',
    sprintId: 'SPR-002',
    createdAt: new Date('2025-09-16'),
    updatedAt: new Date('2025-09-16'),
  },
  {
    id: 'TSK-009',
    title: 'Add export functionality for reports',
    description: 'Allow users to export project reports in PDF and CSV formats',
    priority: 'P3',
    status: 'Todo',
    assignee: 'David Park',
    sprintId: 'SPR-003',
    createdAt: new Date('2025-09-17'),
    updatedAt: new Date('2025-09-17'),
  },
  {
    id: 'TSK-010',
    title: 'Implement dark mode theme',
    description: 'Add system-wide dark mode with user preference persistence',
    priority: 'P2',
    status: 'Todo',
    assignee: 'Sarah Chen',
    sprintId: 'SPR-003',
    createdAt: new Date('2025-09-18'),
    updatedAt: new Date('2025-09-18'),
  },
  {
    id: 'TSK-011',
    title: 'Optimize bundle size',
    description: 'Reduce JavaScript bundle size by implementing code splitting',
    priority: 'P1',
    status: 'Todo',
    assignee: 'Marcus Johnson',
    sprintId: 'SPR-003',
    createdAt: new Date('2025-09-19'),
    updatedAt: new Date('2025-09-19'),
  },
  {
    id: 'TSK-012',
    title: 'Add search functionality to issues',
    description: 'Implement full-text search with filters for issues and tasks',
    priority: 'P2',
    status: 'Todo',
    assignee: 'Lisa Thompson',
    sprintId: null,
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-09-20'),
  },
  {
    id: 'TSK-013',
    title: 'Create user onboarding flow',
    description: 'Design and implement guided tour for new users',
    priority: 'P3',
    status: 'Todo',
    assignee: 'Emily Rodriguez',
    sprintId: null,
    createdAt: new Date('2025-09-21'),
    updatedAt: new Date('2025-09-21'),
  },
  {
    id: 'TSK-014',
    title: 'Fix memory leak in dashboard',
    description: 'Investigate and resolve memory leak causing browser slowdown',
    priority: 'P0',
    status: 'Todo',
    assignee: 'David Park',
    sprintId: null,
    createdAt: new Date('2025-09-22'),
    updatedAt: new Date('2025-09-22'),
  },
  {
    id: 'TSK-015',
    title: 'Add keyboard shortcuts',
    description: 'Implement comprehensive keyboard shortcuts for power users',
    priority: 'P3',
    status: 'Todo',
    assignee: 'Sarah Chen',
    sprintId: null,
    createdAt: new Date('2025-09-23'),
    updatedAt: new Date('2025-09-23'),
  },
  {
    id: 'TSK-016',
    title: 'Improve error handling and messages',
    description: 'Provide clearer error messages and recovery options throughout the app',
    priority: 'P2',
    status: 'Todo',
    assignee: 'Marcus Johnson',
    sprintId: null,
    createdAt: new Date('2025-09-24'),
    updatedAt: new Date('2025-09-24'),
  },
  {
    id: 'TSK-017',
    title: 'Add activity timeline to issues',
    description: 'Show complete history of changes and comments on each issue',
    priority: 'P4',
    status: 'Todo',
    assignee: 'Lisa Thompson',
    sprintId: null,
    createdAt: new Date('2025-09-25'),
    updatedAt: new Date('2025-09-25'),
  },
  {
    id: 'TSK-018',
    title: 'Implement API rate limiting',
    description: 'Add rate limiting to protect API from abuse and ensure fair usage',
    priority: 'P1',
    status: 'Todo',
    assignee: 'Emily Rodriguez',
    sprintId: null,
    createdAt: new Date('2025-09-26'),
    updatedAt: new Date('2025-09-26'),
  },
];
